# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.main.middlewares.grpc_middlewares.protos.user.add_user_account_proto import add_user_account_pb2 as add__user__account__pb2


class AddUserAccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeUserAccountFactory = channel.unary_unary(
                '/add_user_account.AddUserAccount/makeUserAccountFactory',
                request_serializer=add__user__account__pb2.Request.SerializeToString,
                response_deserializer=add__user__account__pb2.Response.FromString,
                )


class AddUserAccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeUserAccountFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddUserAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeUserAccountFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.makeUserAccountFactory,
                    request_deserializer=add__user__account__pb2.Request.FromString,
                    response_serializer=add__user__account__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'add_user_account.AddUserAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddUserAccount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeUserAccountFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/add_user_account.AddUserAccount/makeUserAccountFactory',
            add__user__account__pb2.Request.SerializeToString,
            add__user__account__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
