# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: refuse_exchange.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15refuse_exchange.proto\x12\x0frefuse_exchange\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x14\n\x07message\x18\r \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2b\n\x0eRefuseExchange\x12P\n\x19makeRefuseExchangeFactory\x12\x18.refuse_exchange.Request\x1a\x19.refuse_exchange.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'refuse_exchange_pb2'
  # @@protoc_insertion_point(class_scope:refuse_exchange.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'refuse_exchange_pb2'
  # @@protoc_insertion_point(class_scope:refuse_exchange.Response)
  })
_sym_db.RegisterMessage(Response)

_REFUSEEXCHANGE = DESCRIPTOR.services_by_name['RefuseExchange']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=42
  _REQUEST._serialized_end=63
  _RESPONSE._serialized_start=65
  _RESPONSE._serialized_end=129
  _REFUSEEXCHANGE._serialized_start=131
  _REFUSEEXCHANGE._serialized_end=229
# @@protoc_insertion_point(module_scope)
