run-rest:
	python3 -m src.main.servers.rest.server
run-grpc:
	python3 -m src.main.servers.grpc.server
run-socket:
	python3 -m src.main.servers.socket.server
setup: requirements.txt
	pip3 install -r requirements.txt