# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.user.authenticate_user_proto import authenticate_user_pb2 as authenticate__user__pb2


class AuthenticateUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeAuthenticateUserFactory = channel.unary_unary(
                '/authenticate_user.AuthenticateUser/makeAuthenticateUserFactory',
                request_serializer=authenticate__user__pb2.Request.SerializeToString,
                response_deserializer=authenticate__user__pb2.Response.FromString,
                )


class AuthenticateUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeAuthenticateUserFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticateUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeAuthenticateUserFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.makeAuthenticateUserFactory,
                    request_deserializer=authenticate__user__pb2.Request.FromString,
                    response_serializer=authenticate__user__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authenticate_user.AuthenticateUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthenticateUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeAuthenticateUserFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authenticate_user.AuthenticateUser/makeAuthenticateUserFactory',
            authenticate__user__pb2.Request.SerializeToString,
            authenticate__user__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
