# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticate_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61uthenticate_user.proto\x12\x11\x61uthenticate_user\"-\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x98\x01\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08username\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04name\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07message\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_usernameB\x07\n\x05_nameB\n\n\x08_message2j\n\x10\x41uthenticateUser\x12V\n\x1bmakeAuthenticateUserFactory\x12\x1a.authenticate_user.Request\x1a\x1b.authenticate_user.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'authenticate_user_pb2'
  # @@protoc_insertion_point(class_scope:authenticate_user.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'authenticate_user_pb2'
  # @@protoc_insertion_point(class_scope:authenticate_user.Response)
  })
_sym_db.RegisterMessage(Response)

_AUTHENTICATEUSER = DESCRIPTOR.services_by_name['AuthenticateUser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=46
  _REQUEST._serialized_end=91
  _RESPONSE._serialized_start=94
  _RESPONSE._serialized_end=246
  _AUTHENTICATEUSER._serialized_start=248
  _AUTHENTICATEUSER._serialized_end=354
# @@protoc_insertion_point(module_scope)
