# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add_trade_solicitations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61\x64\x64_trade_solicitations.proto\x12\x17\x61\x64\x64_trade_solicitations\"m\n\x07Request\x12\x18\n\x10received_user_id\x18\x01 \x01(\x05\x12\x16\n\x0esender_user_id\x18\x02 \x01(\x05\x12\x17\n\x0fwant_pokemon_id\x18\x03 \x01(\x05\x12\x17\n\x0fgive_pokemon_id\x18\x04 \x01(\x05\"@\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2\x80\x01\n\x15\x41\x64\x64TradeSolicitations\x12g\n makeAddTradeSolicitationsFactory\x12 .add_trade_solicitations.Request\x1a!.add_trade_solicitations.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'add_trade_solicitations_pb2'
  # @@protoc_insertion_point(class_scope:add_trade_solicitations.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'add_trade_solicitations_pb2'
  # @@protoc_insertion_point(class_scope:add_trade_solicitations.Response)
  })
_sym_db.RegisterMessage(Response)

_ADDTRADESOLICITATIONS = DESCRIPTOR.services_by_name['AddTradeSolicitations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=58
  _REQUEST._serialized_end=167
  _RESPONSE._serialized_start=169
  _RESPONSE._serialized_end=233
  _ADDTRADESOLICITATIONS._serialized_start=236
  _ADDTRADESOLICITATIONS._serialized_end=364
# @@protoc_insertion_point(module_scope)
