# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_user_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17list_user_account.proto\x12\x11list_user_account\"!\n\x07Request\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x05\n\x03_id\"h\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12&\n\x05users\x18\x02 \x03(\x0b\x32\x17.list_user_account.User\x12\x14\n\x07message\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"2\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2h\n\x0fListUserAccount\x12U\n\x1amakeListUserAccountFactory\x12\x1a.list_user_account.Request\x1a\x1b.list_user_account.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_USER = DESCRIPTOR.message_types_by_name['User']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'list_user_account_pb2'
  # @@protoc_insertion_point(class_scope:list_user_account.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'list_user_account_pb2'
  # @@protoc_insertion_point(class_scope:list_user_account.Response)
  })
_sym_db.RegisterMessage(Response)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'list_user_account_pb2'
  # @@protoc_insertion_point(class_scope:list_user_account.User)
  })
_sym_db.RegisterMessage(User)

_LISTUSERACCOUNT = DESCRIPTOR.services_by_name['ListUserAccount']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=46
  _REQUEST._serialized_end=79
  _RESPONSE._serialized_start=81
  _RESPONSE._serialized_end=185
  _USER._serialized_start=187
  _USER._serialized_end=237
  _LISTUSERACCOUNT._serialized_start=239
  _LISTUSERACCOUNT._serialized_end=343
# @@protoc_insertion_point(module_scope)
