# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_user_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19list_user_inventory.proto\x12\x13list_user_inventory\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\xac\x01\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0e\n\x06userid\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x13\n\x0binventoryid\x18\x04 \x01(\x05\x12\x33\n\x0binventories\x18\x05 \x03(\x0b\x32\x1e.list_user_inventory.Inventory\x12\x14\n\x07message\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"I\n\tInventory\x12\x11\n\tpokemonid\x18\x01 \x01(\x05\x12\x13\n\x0bpokemonname\x18\x02 \x01(\t\x12\x14\n\x0cpokemonimage\x18\x03 \x01(\t2p\n\x11ListUserInventory\x12[\n\x1cmakeListUserInventoryFactory\x12\x1c.list_user_inventory.Request\x1a\x1d.list_user_inventory.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_INVENTORY = DESCRIPTOR.message_types_by_name['Inventory']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'list_user_inventory_pb2'
  # @@protoc_insertion_point(class_scope:list_user_inventory.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'list_user_inventory_pb2'
  # @@protoc_insertion_point(class_scope:list_user_inventory.Response)
  })
_sym_db.RegisterMessage(Response)

Inventory = _reflection.GeneratedProtocolMessageType('Inventory', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORY,
  '__module__' : 'list_user_inventory_pb2'
  # @@protoc_insertion_point(class_scope:list_user_inventory.Inventory)
  })
_sym_db.RegisterMessage(Inventory)

_LISTUSERINVENTORY = DESCRIPTOR.services_by_name['ListUserInventory']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=50
  _REQUEST._serialized_end=71
  _RESPONSE._serialized_start=74
  _RESPONSE._serialized_end=246
  _INVENTORY._serialized_start=248
  _INVENTORY._serialized_end=321
  _LISTUSERINVENTORY._serialized_start=323
  _LISTUSERINVENTORY._serialized_end=435
# @@protoc_insertion_point(module_scope)
