# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.trade.trade_pokemon_proto import trade_pokemon_pb2 as trade__pokemon__pb2


class TradePokemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeTradePokemonFactory = channel.unary_unary(
                '/trade_pokemon.TradePokemon/makeTradePokemonFactory',
                request_serializer=trade__pokemon__pb2.Request.SerializeToString,
                response_deserializer=trade__pokemon__pb2.Response.FromString,
                )


class TradePokemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeTradePokemonFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradePokemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeTradePokemonFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.makeTradePokemonFactory,
                    request_deserializer=trade__pokemon__pb2.Request.FromString,
                    response_serializer=trade__pokemon__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trade_pokemon.TradePokemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TradePokemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeTradePokemonFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trade_pokemon.TradePokemon/makeTradePokemonFactory',
            trade__pokemon__pb2.Request.SerializeToString,
            trade__pokemon__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
