# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.trade.add_trade_solicitations_proto import add_trade_solicitations_pb2 as add__trade__solicitations__pb2


class AddTradeSolicitationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeAddTradeSolicitationsFactory = channel.unary_unary(
                '/add_trade_solicitations.AddTradeSolicitations/makeAddTradeSolicitationsFactory',
                request_serializer=add__trade__solicitations__pb2.Request.SerializeToString,
                response_deserializer=add__trade__solicitations__pb2.Response.FromString,
                )


class AddTradeSolicitationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeAddTradeSolicitationsFactory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddTradeSolicitationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeAddTradeSolicitationsFactory': grpc.unary_unary_rpc_method_handler(
                    servicer.makeAddTradeSolicitationsFactory,
                    request_deserializer=add__trade__solicitations__pb2.Request.FromString,
                    response_serializer=add__trade__solicitations__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'add_trade_solicitations.AddTradeSolicitations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddTradeSolicitations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeAddTradeSolicitationsFactory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/add_trade_solicitations.AddTradeSolicitations/makeAddTradeSolicitationsFactory',
            add__trade__solicitations__pb2.Request.SerializeToString,
            add__trade__solicitations__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
