# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add_user_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x64\x64_user_account.proto\x12\x10\x61\x64\x64_user_account\";\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x1e\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x32\x61\n\x0e\x41\x64\x64UserAccount\x12O\n\x16makeUserAccountFactory\x12\x19.add_user_account.Request\x1a\x1a.add_user_account.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'add_user_account_pb2'
  # @@protoc_insertion_point(class_scope:add_user_account.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'add_user_account_pb2'
  # @@protoc_insertion_point(class_scope:add_user_account.Response)
  })
_sym_db.RegisterMessage(Response)

_ADDUSERACCOUNT = DESCRIPTOR.services_by_name['AddUserAccount']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=44
  _REQUEST._serialized_end=103
  _RESPONSE._serialized_start=105
  _RESPONSE._serialized_end=135
  _ADDUSERACCOUNT._serialized_start=137
  _ADDUSERACCOUNT._serialized_end=234
# @@protoc_insertion_point(module_scope)
