# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_pokemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trade_pokemon.proto\x12\rtrade_pokemon\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x14\n\x07message\x18\r \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2Z\n\x0cTradePokemon\x12J\n\x17makeTradePokemonFactory\x12\x16.trade_pokemon.Request\x1a\x17.trade_pokemon.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'trade_pokemon_pb2'
  # @@protoc_insertion_point(class_scope:trade_pokemon.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'trade_pokemon_pb2'
  # @@protoc_insertion_point(class_scope:trade_pokemon.Response)
  })
_sym_db.RegisterMessage(Response)

_TRADEPOKEMON = DESCRIPTOR.services_by_name['TradePokemon']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=38
  _REQUEST._serialized_end=59
  _RESPONSE._serialized_start=61
  _RESPONSE._serialized_end=125
  _TRADEPOKEMON._serialized_start=127
  _TRADEPOKEMON._serialized_end=217
# @@protoc_insertion_point(module_scope)
